### ISSUE TITLE
undefined method 'define_simple_form_attributes'

### ISSUE THREAD

**Issue by activestylus** [heartcombo/simple_form#154]
I get this error ever since I upgraded to 1.3.0 (was on 1.2.2)

Currently this is not working at all with Rails 3.0.3

Any ideas?
