### ISSUE TITLE
f.hint broken in 1.3.0

### ISSUE THREAD

**Issue by olegueret** [heartcombo/simple_form#142]
This worked fine in 1.2.2:

```
<%= f.hint "hello" %>
```

and also this:

```
<%= f.hint render(:partial => 'guides/hint/custom_maps'), :style=>'margin-left:2em;' %>
```

But in 1.3.0, every f.hint I try raises an exception (look for references of line 70):

```
ActionView::Template::Error (undefined method `to_sym' for nil:NilClass):
    67:         <span id="location_coordinates"><%= location_coordinates(@guide.location) || _('Location not set') %></span>
    68:       </div>
    69:     </div>
    70:     <%= f.hint "hello" %>
    71:     
    72:   </div>
    73:   <%= f.error :location, :id => 'guide_location_error' %>
  app/views/guides/step/_maps.html.erb:70:in `block in _app_views_guides_step__maps_html_erb___655456839_83104020_591517806'
  app/views/guides/step/_maps.html.erb:53:in `_app_views_guides_step__maps_html_erb___655456839_83104020_591517806'
  app/controllers/guides_controller.rb:50:in `map_info'

Rendered /home/oleguer/.rvm/gems/ruby-1.9.2-p0@woicesguides/gems/actionpack-3.0.3/lib/action_dispatch/middleware/templates/rescues/_trace.erb (2.0ms)
Rendered /home/oleguer/.rvm/gems/ruby-1.9.2-p0@woicesguides/gems/actionpack-3.0.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (147.0ms)
Rendered /home/oleguer/.rvm/gems/ruby-1.9.2-p0@woicesguides/gems/actionpack-3.0.3/lib/action_dispatch/middleware/templates/rescues/template_error.erb within rescues/layout (156.9ms)
```
